### ISSUE TITLE
Not enough space to install error

### ISSUE THREAD

**Issue by MacAttack-UK** [7D2DModLauncher/ThickInstaller#1]
![7d2dlauncher-df_error](https://user-images.githubusercontent.com/13574886/51627729-f5911100-1f3a-11e9-9ac6-3d282a30d594.jpg)

After updating the launcher and changing the mod install drive to D: I get the above error.

I've tried uninstall/re-install and get the same, it's still giving me not enough space error when I quite clearly have 296GB free. The drive that has 4GB free is my steam library folder so I'm a little confused as to why it's trying to install on there when I've told it to use D:

**Comment by SphereII** [comment]
It must be looking at the wrong drive. I'll push an update in a few minutes to fix this for you.

**Comment by MacAttack-UK** [comment]
Thank you for the fast fix, it is now installing where it should.

**Comment by SphereII** [comment]
Thanks for taking the time to let me know :)
